name: Run Script on Ubuntu

on:
  push:
    branches: [ main ]

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup
        run: |
          apt update
          apt install zsh -y
          zsh --version
      - name: Run script
        run:
          ./setup.sh