name: Setup Smoke Tests
on:
  pull_request:
  workflow_dispatch:

jobs:
  smoke:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install test dependencies
        run: brew install stow
      - name: Smoke test setup
        run: |
          ./main.sh test
