name: Run Script on macOS
on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup
        run: |
          ./main.sh setup