name: Run Script on macOS

on:
  push:
    branches: [ main ]

jobs:
  run-script:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup
        run: |
          ./setup.sh